name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 13.x
        uses: actions/setup-node@v3
        with:
          node-version: 13.12

      - name: Run install
        run: yarn install
      - name: Build
        run: yarn build-prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
